### ISSUE TITLE
The client doesn't start in ubuntu 12.04 LTS 64 bits

### ISSUE THREAD

**Issue by acafresna** [desura/desura-app#971] opened 2015-01-05 17:53 UTC
After succesfully installing and updating the client downloaded from http://www.desura.com/desura-x86_64.tar.gz , I get the following error when trying to run desura:

    ff@kant:/home/ff/juegos/desura$ ./desura
    Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!

And then it ends. I am running ubuntu 12.04 64 bits with kernel 3.2.0-74-generic

**Comment by TheSentry** [comment] 2015-01-07 20:31
Same system, same error :(

**Comment by TheBeastie** [comment] 2015-01-07 23:18
TheSentry, we have updated the Linux Desura App to 120.25, which should have fixed some installation crashes and various crashes while running.   Would you mind seeing if this version works for you?

**Comment by acafresna** [comment] 2015-01-08 09:35
In case you are interested, I tested today again and this time I get this error:

    ff@kant:~/juegos/desura$ ./desura
    Failed to update desktop icon. Could not open file for writing
    /home/ff/juegos/desura/lib/desura: error while loading shared libraries: libboost_filesystem.so.1.54.0: cannot open shared object file: No such file or directory

In precise pangoling repositories there is libboost-filesystem1.48.0  and libboost-filesystem1.46.1 I will try later to install 1.54 by hand.

**Comment by TheSentry** [comment] 2015-01-08 15:16
@TheBeastie You updated the one here I have to compile myself? Or the binary I can download from the website?

**Comment by codethulu** [comment] 2015-01-19 17:52
This issue should be resolved in 320.31/120.26. Please re-open if this persists after an update.

**Closed by codethulu** 2015-01-19 17:52 UTC

**Comment by TheSentry** [comment] 2015-01-19 22:03
It persists. I downloaded the binary from http://www.desura.com/desura-x86_64.tar.gz, extracted it into the desura folder and ran './desura'. It downloaded an update and then I get:

    Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!

**Comment by TheSentry** [comment] 2015-10-17 15:43
It is now October and the issue is still present

**Comment by codethulu** [comment] 2015-10-17 18:00
You're aware that the organization went bankrupt and no one is backing this project, yes?

**Comment by TheSentry** [comment] 2015-10-17 19:06
No, I'm not. So do you reopen the ticket?

**Comment by codethulu** [comment] 2015-10-17 20:24
No. This, and any other issues with the project will likely never be resolved. But it's a moot point, because the service the project is supporting is defunct.

**Comment by TheSentry** [comment] 2015-10-17 22:39
That's a shame ... thanks anyway. I will do a fresh install of a newer Ubuntu anyway, this will probably solve it.
