### ISSUE TITLE
Doesn't run due libboost_filesystem

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#993] opened 2015-01-17 13:51 UTC
I downloaded the latest client, but now it doesn't run the client due to needing:
libboost_filesystem.so.1.54.0

And that isn't installed by default. So, it might be an idea to include it with Desura?

**Comment by acafresna** [comment] 2015-01-17 14:55
I reported this a few days ago too, it is in my last comment https://github.com/desura/desura-app/issues/971

**Comment by codethulu** [comment] 2015-01-19 17:51
duplicate of #971

**Closed by codethulu** 2015-01-19 17:51 UTC
